steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/recommendation-engine:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/recommendation-engine:$COMMIT_SHA']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=k8s/
  - --image=gcr.io/$PROJECT_ID/recommendation-engine:$COMMIT_SHA
  - --location=${_REGION}
  - --cluster=${_CLUSTER_NAME}

substitutions:
  _REGION: us-central1
  _CLUSTER_NAME: recommendation-cluster

images:
- gcr.io/$PROJECT_ID/recommendation-engine:$COMMIT_SHA 