[build]
name = "ai-recommendation-api"
builder = "nixpacks"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 10
healthcheckInterval = 30
numReplicas = 1
healthcheckProtocol = "http"

[deploy.envs]
PYTHON_VERSION = "3.9"
PORT = "8080"
ENVIRONMENT = "production"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "INFO"