[build]
name = "ai-recommendation-api"
builder = "nixpacks"
dockerfilePath = "Dockerfile"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 100
healthcheckInterval = 30
numReplicas = 1
healthcheckProtocol = "http"

[deploy.envs]
PYTHON_VERSION = "3.9"
PORT = "8080"
ENVIRONMENT = "production"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "INFO"