[build]
name = "ai-recommendation-api"
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 15
numReplicas = 2
minReplicas = 1
maxReplicas = 5
healthcheckProtocol = "http"

[deploy.envs]
PYTHON_VERSION = "3.9"
PORT = "8080"
ENVIRONMENT = "production"
PYTHONUNBUFFERED = "1"
LOG_LEVEL = "INFO"

[deploy.resources]
memory = "512Mi"
cpu = "250m"