services:
  - type: web
    name: ai-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: MONGODB_URI
        value: mongodb+srv://[USERNAME]:[PASSWORD]@[CLUSTER].mongodb.net/[DB_NAME] 