services:
  - type: web
    name: ai-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: MONGODB_URI
        value: mongodb+srv://[USERNAME]:[PASSWORD]@[CLUSTER].mongodb.net/[DB_NAME]
      # Supabase Configuration
      - key: SUPABASE_URL
        value: your-project-ref
      - key: SUPABASE_KEY
        value: your-supabase-anon-key
      - key: SUPABASE_JWT_SECRET
        value: your-supabase-jwt-secret
      # Redis Configuration
      - key: REDIS_HOST
        value: your-redis-host
      - key: REDIS_PORT
        value: "6379"