services:
  - type: web
    name: ai-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      # MongoDB
      - key: MONGODB_URI
        value: "mongodb+srv://[USERNAME]:[PASSWORD]@[CLUSTER].mongodb.net/[DB_NAME]"
      - key: MONGODB_DB_NAME
        value: "recommendation_engine"
      # Redis
      - key: REDIS_HOST
        value: "your-redis-host"
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: "your-redis-password"
      # Supabase
      - key: SUPABASE_URL
        value: "your-project-ref"
      - key: SUPABASE_KEY
        value: "your-supabase-anon-key"
      - key: SUPABASE_JWT_SECRET
        value: "your-supabase-jwt-secret"
      # Auth
      - key: SECRET_KEY
        generateValue: true
      # Service URLs
      - key: FRONTEND_URL
        value: "https://your-frontend.vercel.app"