services:
  - type: web
    name: ai-recommendation-api
    env: python
    region: ohio
    plan: free
    buildCommand: pip install --upgrade pip && pip install PyJWT pydantic-settings && pip install -r requirements.txt && python app/setup_app.py
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_PATH
        value: models/latest
      - key: CONTENT_PATH
        value: data/processed/movielens-small
    healthCheckPath: /health

databases:
  - name: ai-recommendation-db
    plan: starter
    ipAllowList: []