services:
  - type: web
    name: ai-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ENVIRONMENT
        value: production
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      # Redis
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      # Frontend URL (Vercel)
      - key: FRONTEND_URL
        value: https://ai-powered-content-recommendation-frontend.vercel.app
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 75

databases:
  - name: postgres
    ipAllowList: []
    
services:
  - type: redis
    name: redis
    ipAllowList: []
    plan: starter