services:
  - type: web
    name: ai-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: ai-recommendation-db
          property: host
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: ai-recommendation-db
          property: database
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: ai-recommendation-db
          property: password
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: MODEL_SERVICE_URL
        value: https://your-model-service.onrender.com

databases:
  - name: ai-recommendation-db
    databaseName: ai_recommendation
    user: ai_recommendation