services:
  - type: web
    name: ai-recommendation-api
    env: python
    region: ohio
    plan: free
    buildCommand: >
      pip install --upgrade pip &&
      pip install PyJWT>=2.4.0 python-jose>=3.3.0 passlib>=1.7.4 python-multipart>=0.0.5 &&
      pip install fastapi>=0.100.0 uvicorn>=0.18.0 pydantic>=2.0.0 pydantic-settings>=2.0.0 email-validator>=2.0.0 &&
      pip install "sqlalchemy[asyncio]>=1.4.0" psycopg2-binary>=2.9.3 &&
      pip install redis>=4.2.0 &&
      pip install -r requirements.txt &&
      python app/setup_app.py
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_PATH
        value: models/latest
      - key: CONTENT_PATH
        value: data/processed/movielens-small
    healthCheckPath: /health

databases:
  - name: ai-recommendation-db
    plan: starter
    ipAllowList: []